

# Overall filter
base_frame_id:    robot_footprint
global_frame_id:  map
min_particles:    15
max_particles:    450
initial_pose_x:   0.0
initial_pose_y:   0.0
initial_pose_a:   0.0

# Laser
laser_model_type: likelihood_field
laser_z_hit:      0.997
laser_z_rand:     0.003
laser_max_beams:  90
laser_min_range:  0.3
# Odometry
odom_frame_id:    odom
odom_model_type:  omni
odom_alpha1:      0.05
odom_alpha2:      0.05
odom_alpha3:      0.05
odom_alpha4:      0.05
odom_alpha5:      0.05
