local_costmap:
   global_frame:      odom
   robot_base_frame:  robot_footprint
   update_frequency:  15.0
   publish_frequency: 15.0
   width:             3.0
   height:            3.0
   resolution:        0.02
   static_map:        false
   rolling_window:    true
