local_costmap:
   global_frame:      odom
   robot_base_frame:  robot_footprint
   update_frequency:  5.0
   publish_frequency: 5.0
   width:             4.0
   height:            4.0
   resolution:        0.02
   static_map:        false
   rolling_window:    true
